### ISSUE TITLE
Script to check for prerequisites

### ISSUE THREAD

**Issue by lskatz** [lskatz/SneakerNet#14]
**Is your feature request related to a problem? Please describe.**
It is difficult to tell whether all prerequisite software is in my PATH before kicking off SneakerNet.

**Describe the solution you'd like**
I would like a script to detect all prerequisite software and versions.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kapsakcj** [comment]
I second this 👍 

Perhaps take a similar approach to Shovill's dependency check? https://github.com/tseemann/shovill/blob/master/bin/shovill#L456

**Comment by kapsakcj** [comment]
also relevant, a little bit higher up in the same perl script https://github.com/tseemann/shovill/blob/master/bin/shovill#L39

**Comment by lskatz** [comment]
Good find, @kapsakcj !  Thank you!

**Comment by lskatz** [comment]
I am thinking of adding `--check-dependencies` for each plugin to make them independent, and then potentially a wrapper script to check all the dependencies.

**Comment by lskatz** [comment]
* `--check-dependencies` has been added to all plugins
* `--check-dependencies` has been added to the documentation
* `t/90_universalOptionsInPlugins.t` checks for it
* `SneakerNet.checkdeps.pl` is now available.  It simply loops through all plugins and checks for dependencies.  Useful for checking dependencies before a lengthy run.
