### ISSUE TITLE
bcl2fastq missed

### ISSUE THREAD

**Issue by kapsakcj** [lskatz/SneakerNet#30]
**Describe the bug**
bcl2fastq isn't checked for in checkdeps.pl scripts, or listed in the install.md docs

I also did not put it in the Dockerfile

**To Reproduce**
```
docker run --rm -v $PWD:/data -u $(id -u):$(id -g) lskatz/sneakernet:latest SneakerNet.roRun.pl /data/$MISEQ -o /data/$INDIR
SneakerNet.roRun.pl: ERROR: no interop files were found in /data/miseq-rundir/
SneakerNet.roRun.pl: snok.txt not found. I will not read from it.
SneakerNet.roRun.pl: WARNING: no fastq files were found; attempting bcl2fastq
sh: 1: bcl2fastq: not found
```

**Expected behavior**
bcl2fastq needs to be listed in docs

It also needs to be added to the dockerfile and added to the PATH as specified in dockerfile

**Comment by kapsakcj** [comment]
I will do a PR to add bcl2fastq to the Dockerfile

**Comment by lskatz** [comment]
Added PR from @kapsakcj in 29fff06e5141d19b3680e954b822da53a6aada98 and added documentation in 09d4821e703249d56f36a3d4d53de6d22ad33afb
