### ISSUE TITLE
Please complete the Apache license copyright field

### ISSUE THREAD

**Issue by lfaller** [lskatz/SneakerNet#38]
Hello! I am a reviewer for [your tool](https://github.com/openjournals/joss-reviews/issues/2334) in the JOSS 👋 

I noticed that you forgot to fill in the copyright line in your Apache license text file:

https://github.com/lskatz/SneakerNet/blob/e590634435fea3c6437d4061d66c3f259579fa48/LICENSE#L189

Would be great if you could fill in that information.

Cheers,
~Lina

**Comment by lskatz** [comment]
Thank you for pointing that out!  Fixed in 2d4e3eea29a26c60c90c6fc75af517cc7b1826eb.
