### ISSUE TITLE
Pipeline does not exit gracefully if sample files are listed in sample sheet but no FASTQ data is present

### ISSUE THREAD

**Issue by lfaller** [lskatz/SneakerNet#40]
**Describe the bug**

The pipeline does not exit gracefully if a sample is listed in the sample sheet but no FASTQ files are present (at least I think this is the problem). When this happens, it is not clear if the pipeline crashed. If the pipeline did indeed crash, it is not clear if the data can be trusted or used as is, or if something has to be fixed before using the data that has so far been generated.

**To Reproduce**

```
cd /path/to/repo/SneakerNet/t

export MISEQ=M00123-18-001-test
export INDIR=M00123-18-001-test

docker run --rm -v $PWD:/data -u $(id -u):$(id -g) lskatz/sneakernet:latest SneakerNetPlugins.pl --numcpus 4 --no email --no transfer --no save $INDIR
```

**Expected behavior**

I think the warning message is actually pretty good:

```
sn_kraken.pl: WARNING: I could not find the reads for contaminated .
Can't use string ("") as an ARRAY ref while "strict refs" in use at /SneakerNet-0.9.10/scripts/../SneakerNet.plugins/sn_kraken.pl line 114.
SneakerNetPlugins.pl: ERROR with plugin sn_kraken.pl: ERROR running command
  /SneakerNet-0.9.10/scripts/../SneakerNet.plugins/sn_kraken.pl . --numcpus 4 at /SneakerNet-0.9.10/scripts/SneakerNetPlugins.pl line 99.
```

However, the message `Can't use string ("")...` should not be shown to the user because it could be handled by catching an exception (the exception could be raised by the fact that no read FASTQ files have been identified).

The error message should clarify that kraken could not be run on this sample because there were no read files present.

It is also not clear if the error encountered while attempting to run kraken now crashed the pipeline or if this is the end of the pipeline. 

Finally, you could suggest a fix to the user: double-check your sample sheet and make sure all the FASTQ files for your samples are present.

**Log output**

```
...
[22:51:07] Found exact allele match neisseria.abcZ-109
[22:51:07] Found exact allele match neisseria.gdh-147
[22:51:07] Using label 'FA1090.skesa.fasta' for file ./SneakerNet/assemblies/FA1090/FA1090.skesa.fasta
[22:51:07] I am quite confident this won't be the last time you run mlst.
[22:51:07] Done.
[22:51:08] Found exact allele match ecoli.fumC-532
[22:51:08] Found exact allele match ecoli.icd-40
[22:51:08] Found exact allele match senterica.purE-5
[22:51:08] Found exact allele match senterica.thrA-2
[22:51:08] Found exact allele match senterica.hemD-12
[22:51:08] Found exact allele match ecoli.purA-177
[22:51:08] Found exact allele match senterica.hisD-9
[22:51:08] Found exact allele match senterica.dnaN-7
[22:51:08] Found exact allele match ecoli.gyrB-213
[22:51:08] Found exact allele match senterica.sucA-9
[22:51:08] Found exact allele match senterica.aroC-10
[22:51:08] Using label 'LT2.skesa.fasta' for file ./SneakerNet/assemblies/LT2/LT2.skesa.fasta
[22:51:08] Somehow this tool escaped my normal Australiana based naming system.
[22:51:08] Done.
sn_kraken.pl: Running Kraken on LT2
sn_kraken.pl:   Database: /kraken-database/minikraken_20171013_4GB
100000 sequences (50.10 Mbp) processed in 32.120s (186.8 Kseq/m, 93.59 Mbp/m).
  99989 sequences classified (99.99%)
  11 sequences unclassified (0.01%)
sn_kraken.pl: Running Kraken on contaminated
sn_kraken.pl:   Database: /kraken-database/minikraken_20171013_4GB
sn_kraken.pl: WARNING: I could not find the reads for contaminated .
Can't use string ("") as an ARRAY ref while "strict refs" in use at /SneakerNet-0.9.10/scripts/../SneakerNet.plugins/sn_kraken.pl line 114.
SneakerNetPlugins.pl: ERROR with plugin sn_kraken.pl: ERROR running command
  /SneakerNet-0.9.10/scripts/../SneakerNet.plugins/sn_kraken.pl . --numcpus 4 at /SneakerNet-0.9.10/scripts/SneakerNetPlugins.pl line 99.

Who are you?
SneakerNetPlugins.pl: ERROR email failed to send to nobody@cdc.gov,another@cdc.gov
```

**Desktop (please complete the following information):**
 - OS: MacOS X 10.13.6 
 - Docker: 2.3.0.3

**Comment by lskatz** [comment]
Added a fix but have not fully validated it yet, and so I will keep the issue open so far.  d553e9e

**Comment by lskatz** [comment]
One more fix (still unvalidated) to set up the environment for container-based runs in f2e040e

**Comment by lskatz** [comment]
ok!  I fixed a few more small things and I believe it is all graceful in warnings related to this issue.  All of this is now contained in v0.10.3 (8026ed97c207aac5138a12579d3e010b6d0d436d).
