### ISSUE TITLE
Please consider fully moving to docker for installation purposes

### ISSUE THREAD

**Issue by lfaller** [lskatz/SneakerNet#41]
Hello! 

I have some feedback regarding the installation process.

I was trying to follow the "quick installation" instructions outlined [here](https://github.com/lskatz/SneakerNet/blob/master/docs/INSTALL.md). 

I started with a clean ubuntu box from docker (`docker run -it ubuntu bash`) and after an hour of trying to get the dependencies set up I gave up. 

I would recommend you move the installation process fully to docker to enable users of your software to get started quicker.

I appreciate that you provide information regarding using docker [here](https://github.com/lskatz/SneakerNet/blob/master/docs/CONTAINERS.md). However, I would suggest you provide more detail around the example data to get the user started up quicker.

Right now, the document lists obscure input directories:

```
# this assumes that your miseq run directory, and desired SneakerNet input directory are in your PWD.
# you will need to adjust PATHs depending on where your data is located
export MISEQ=my/miseq/run/dir
export INDIR=my/sneakernet/run/dir
``` 

It is not clear what should be in these directories unless you are familiar with a miseq run directory. This can be difficult for someone who is not as familiar with Illumina data generation. Similarly, what does it mean to have a SneakerNet input directory? It is called "input directory" -- what should that input be? Sequences? Databases? etc Also, where will the output be stored? 

Ideally, example data should be bundled with the docker image so that the user doesn't need to download extra data (maybe someone wants to try your software but doesn't have ready access to Illumina miseq data). Then the user can get started with four lines of code:

```
# get the docker image
docker pull lskatz/sneakernet:latest

# test the software
docker run --rm ... test

# run with example data
docker run --rm ... example

# run with your own data
docker run --rm -v ... my_data
```

By the way, I saw that you have more documentation in the `docs/` subdirectory. This is a great resource, but it requires the user to do some digging to get started. I would argue for simplifying this information to make it more easily digestible.

Finally, I would move the above 4 line docker-based installation to the front page of your github repo. I imagine someone interested in using the software would find information about the installation most useful, and the first thing they will look at is the general README of the github repo. With so much open source software out there, software that is easy to install and use will get the most traction. 

Anyways, I hope you find this feedback useful. 

Related Issue: https://github.com/openjournals/joss-reviews/issues/2334

**Comment by lskatz** [comment]
Hi @lfaller and @erinyoung, thank you for these comments.

I have released v0.11.1 which has improvements on Docker and the documentation as suggested:
* better description of the MiSeq directory
* Better quickstart with Docker in the main `README.md`
* `README.md` for the docs subdirectory, to make a catalog of help files
* A link at the bottom of `README.md` to `docs/README.md` 
* Pushed some wording from CONTAINERS.md to main README.md

**Comment by kapsakcj** [comment]
Hi @lfaller , thanks for the feedback. Do you have access to a computer with more than 1.94GB of RAM? It looks like `shovill` is running out of RAM for each of the samples included in the test data.

Through the benchmarks that @lskatz completed, he found that roughly 4GB minimum of RAM is required to run SneakerNet, and that it it benefits by having more RAM available (recommends 8GB or more)  https://github.com/lskatz/SneakerNet/blob/master/docs/INSTALL.md#resources

----

>Looks like shovill is not happy. Since this is an early step in the pipeline, does that mean nothing will work?

Some of the steps of the SneakerNet pipeline will run with no errors even if `shovill` fails, but some of the steps do require a genome assembly, which is the output of `shovill`. @lskatz has configured SneakerNet to keep progressing even if a step, like `shovill` for example, fails.

I was able to replicate similar, but not exact issues when I limited the docker container to 2GB of RAM. Using this command: 
```
docker run -m 2g --rm -v $PWD:/data -v $KRAKEN_DEFAULT_DB:/kraken-database -u $(id -u):$(id -g) lskatz/sneakernet:latest SneakerNetPlugins.pl --numcpus 2 --no email --no transfer --no save /data/$INDIR &> log-2gbRAMlimit.txt`
```
Pilon failed here (one step in the shovill pipeline):
```
...
[shovill] Running: (bwa mem -v 3 -x intractg -t 2 skesa.fasta R1.fq.gz R2.fq.gz | samclip --ref skesa.fasta.fai | samtools sort --threads 1 -m 16384m --reference skesa.fasta -T /tmp/4qpjxLO0My/samtools.119 -o shovill.bam) 2>&1 | sed 's/^/[bwa+samtools-sort] /' | tee -a shovill.log
[shovill] Running: samtools index shovill.bam 2>&1 | sed 's/^/[samtools-index] /' | tee -a shovill.log
[shovill] Correcting errors in skesa.fasta
[shovill] Running: pilon --genome skesa.fasta --frags shovill.bam --minmq 60 --minqual 3 --fix bases --output pilon --threads 2 --changes --mindepth 0.25 2>&1 | sed 's/^/[pilon] /' | tee -a shovill.log
Killed
[shovill] Could not open pilon.changes
assembleAll.pl: shovill failed!
ERROR running command
  shovill --outdir /tmp/assembleAll.pl.X277QU/contaminated --R1 /data/testing_out/contaminated_1.fastq.gz --R2 /data/testing_out/contaminated_2.fastq.gz --assembler skesa --cpus 2 --keepfiles at /SneakerNet-0.11.2/scripts/../SneakerNet.plugins/assembleAll.pl line 288.

assembleAll.pl: ASSEMBLE SAMPLE LT2
...
```

When I allow for more RAM (125GB on my machine, no limit imposed) SneakerNet runs with no errors. I've attached the logfile from this, to give an example of the expected output. I used the same commands that you have listed above:
```
docker run --rm -v $PWD:/data -v $KRAKEN_DEFAULT_DB:/kraken-database -u $(id -u):$(id -g) lskatz/sneakernet:latest SneakerNetPlugins.pl --numcpus 2 --no email --no transfer --no save /data/$INDIR &> log.txt
```
[log.txt](https://github.com/lskatz/SneakerNet/files/5118608/log.txt)

----

Regarding this comment:
> Maybe it indeed failed completely. It didn't generate a report:
> 
> ```shell
> $> tail log.txt
> sn_passfail.pl: The pass/fail file is under ./SneakerNet/forEmail/passfail.tsv
> sn_report.pl: /data/testing_out/SneakerNet/forEmail/QC_summary.tsv
> sn_report.pl: /data/testing_out/SneakerNet/forEmail/passfail.tsv
> sn_report.pl: /data/testing_out/SneakerNet/forEmail/staramr.tsv
> sn_report.pl: /data/testing_out/SneakerNet/forEmail/basebalance.tsv
> sn_report.pl: /data/testing_out/SneakerNet/forEmail/kraken.tsv
> sn_report.pl: /data/testing_out/SneakerNet/forEmail/mlst.tsv
> sn_report.pl: /data/testing_out/SneakerNet/forEmail/assemblyMetrics.tsv
> sn_report.pl: /data/testing_out/SneakerNet/forEmail/readMetrics.tsv
> sn_report.pl: Report can be found in ./SneakerNet/forEmail/report.html
> 
> $> ls -lah ./SneakerNet/forEmail/report.html
> ls: ./SneakerNet/forEmail/report.html: No such file or directory
> ```
SneakerNet isn't aware that it is running inside a docker container, so the output PATH that it prints above ^ is deceiving. Since you specified your `$PWD` on your host system to mount to `/data` inside the container you should find the report within this directory on your host system: `$PWD/testing_out/SneakerNet/forEmail/report.html` after SneakerNet finishes running and the container exits.

Please let us know if you have more questions or encounter any more issues.

Curtis

**Comment by lfaller** [comment]
Thanks for the example log, it's helpful to see what I should be expecting!

I increased the resources for Docker to 6 CPUs and 11 GB of RAM.

I am still running into issues with shovill, but I think that's due to not enough RAM:

```
assembleAll.pl: Temporary directory is at /tmp/assembleAll.pl.Hw82B9
assembleAll.pl: ASSEMBLE SAMPLE Philadelphia_CDC
assembleAll.pl: Assembling Philadelphia_CDC
[shovill] Hello stranger
[shovill] You ran: /shovill-1.0.4/bin/shovill --outdir /tmp/assembleAll.pl.Hw82B9/Philadelphia_CDC --R1 /data/testing_out/Philadelphia_CDC_1.fastq.gz --R2 /data/testing_out/Philadelphia_CDC_2.fastq.gz --assembler skesa --cpus 2 --keepfiles
[shovill] This is shovill 1.0.4
[shovill] Written by Torsten Seemann
[shovill] Homepage is https://github.com/tseemann/shovill
[shovill] Operating system is linux
[shovill] Perl version is v5.22.1
[shovill] Machine has 6 CPU cores and 10.72 GB RAM
[shovill] Set --ram to 32 but machine only has 10.72 GB
assembleAll.pl: shovill failed!
ERROR running command
  shovill --outdir /tmp/assembleAll.pl.Hw82B9/Philadelphia_CDC --R1 /data/testing_out/Philadelphia_CDC_1.fastq.gz --R2 /data/testing_out/Philadelphia_CDC_2.fastq.gz --assembler skesa --cpus 2 --keepfiles at /SneakerNet-0.11.2/scripts/../SneakerNet.plugins/assembleAll.pl line 288.
```

I think it would be great to make the memory setting for shovill dynamic if that is possible, but at this point I'd call it a "nice to have". It really does seem to be better to run the pipeline on a high-memory machine 🙂
