### ISSUE TITLE
Consider adding information about compute resources needed

### ISSUE THREAD

**Issue by lfaller** [lskatz/SneakerNet#42]
I noticed that the docker image is over 3 Gb when downloaded from dockerhub.

I know some of the tools that SneakerNet uses ship with their own databases. Is that the reason for the size of the docker image? 

In order to pare down the docker image, you could consider if these databases are all needed, or if some of them could be optional for the user. You can also look at [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) and [docker buildkit](https://docs.docker.com/develop/develop-images/build_enhancements/) to try and optimize your docker image.

In general, it would be useful to see an overview of compute resources required to run a basic out-of-the-box SneakerNet analysis.

Related Issue: https://github.com/openjournals/joss-reviews/issues/2334

**Comment by lskatz** [comment]
Hi @lfaller and @erinyoung, 

I have removed the Kraken database from the container between v0.10 and v0.11 and the size of the container dropped significantly.  There are also instructions in CONTAINERS.md on how to link a Kraken database when running the SneakerNet container.

I am still benchmarking but wanted to give an update before the end of the week.  Thank you for your comments.

**Comment by lfaller** [comment]
That sounds great, thanks for the update @lskatz !

**Comment by lskatz** [comment]
For sure, @lfaller !  Thank you for your helpful comments and suggestions!

> In general, it would be useful to see an overview of compute resources required to run a basic out-of-the-box SneakerNet analysis.

I benchmarked SneakerNet on the test data (four genomes at 10x + one contaminated genome which is a mixture of two of the genomes).  These benchmarks were performed on a 72-cpu computer to help avoid any collision of resources in the concurrent test.  Benchmarks were measured with `time --verbose`.

    for i in 1 2 4 8 16 32; do 
      cp -r M00123-18-001-test M00123-18-001-test-$i{cpu}
      \time --verbose singularity exec -B $PWD:/data -B $KRAKEN_DEFAULT_DB:/kraken-database sneakernet.0.11.2.sif SneakerNetPlugins.pl --numcpus $i --no email --no transfer --no save --no immediate M00123-18-001-test-${i}cpu > benchmark.${i}cpus.log 2>&1 &
     done;

With four threads (something I would assume to be reasonable for many or most people) and using the container version of v0.11.2, I think the most relevant stats are that it took about 17 minutes to complete and about 6.2G of RAM with 4 cpus.  I am attaching the full benchmarks for review.

[benchmark.1cpus.log](https://github.com/lskatz/SneakerNet/files/5058036/benchmark.1cpus.log)
[benchmark.2cpus.log](https://github.com/lskatz/SneakerNet/files/5058037/benchmark.2cpus.log)
[benchmark.4cpus.log](https://github.com/lskatz/SneakerNet/files/5058038/benchmark.4cpus.log)
[benchmark.8cpus.log](https://github.com/lskatz/SneakerNet/files/5058039/benchmark.8cpus.log)
[benchmark.16cpus.log](https://github.com/lskatz/SneakerNet/files/5058034/benchmark.16cpus.log)
[benchmark.32cpus.log](https://github.com/lskatz/SneakerNet/files/5058035/benchmark.32cpus.log)

I am also extracting the RAM and time per cpu in this graph, where the first Y-axis is maximum RAM used and the second Y-axis is time elapsed.

![image](https://user-images.githubusercontent.com/14798/89922155-a702a080-dbcc-11ea-9ef0-b2f78535d06d.png)

**Comment by lskatz** [comment]
Note: I am running up to 5 or 10 replicates in case it makes the graph any more informative and to help "average out" any outliers, and I should have results soon.

**Comment by lskatz** [comment]
I went big and ran 100 replicates on our HPC.  Please let me know if I addressed all comments on this issue or if there is any followup, which I would be glad to address.

![image](https://user-images.githubusercontent.com/14798/90025706-6d8d6c00-dc84-11ea-8a0d-bd706d59eac5.png)

cpus | mem (kb) | stddev | seconds | stddev
-- | -- | -- | -- | --
1 | 4312189 | 512452.8 | 1215.39 | 231.1566
2 | 4743979 | 859988.6 | 767.87 | 268.9702
4 | 5442763 | 805141.1 | 583.5 | 221.5411
8 | 6114553 | 727898.3 | 466.07 | 158.9255
16 | 6612363 | 490417.6 | 430.88 | 189.8042
32 | 6768286 | 441932.5 | 392.4 | 277.2188

The HPC benchmarking script is below.

```bash
#!/bin/bash
set -e
set -u

for rep in {1..100}; do
  logfolder=rep$rep.qsub;
  [[ ! -d $logfolder ]] && mkdir $logfolder;
  for cpus in 1 2 4 8 16 32; do
    outdir="M00123-18-001-test-${cpus}cpu-${rep}rep"
    logfile="$logfolder/benchmark.${cpus}cpus.log"

    if [[ -e "$logfile" ]]; then

      exit_code=$(grep "Exit status" < $logfile | grep '[0-9]' | true)
      if [[ "$exit_code" == 0 ]]; then
        echo "Found $logfile completed, exit code $exit_code. Skipping.";
        continue
      fi
    fi

    # We are now moving forward because either the logfile
    # is not present or we ran into an error on a node.

    # Delete old logfile
    if [ -e "$logfile" ]; then
      mv -v $logfile $logfile.tmp && rm -v $logfile.tmp &
    fi

    # Submit the job with the appropriate CPUs.
    # Use fast scratch storage.
    qsub -q edlb.q -pe smp $cpus -cwd -V -N "benchmark${cpus}_${rep}" -o $logfolder/benchmark.${cpus}cpus.log -j y -v "KRAKEN_DEFAULT_DB=$KRAKEN_DEFAULT_DB" -v "outdir=$outdir" <<- "END_OF_SCRIPT"
#!/bin/bash
      set -e
      #set -x
      set -u
      which singularity
      hostname
      echo "";

      # Make the folder
      rm -rf $outdir
      outdirAbs=/scratch/$USER/SneakerNetTest/$outdir
      mkdir -pv $(dirname $outdir)
      cp -rv M00123-18-001-test $outdirAbs
      rm -rf $outdirAbs/SneakerNet $outdirAbs/readMetrics.tsv

      tree -L 2 $outdir

      trap ' { rm -rf $outdir; } ' EXIT

      echo ""
      /usr/bin/time --verbose singularity exec -B /scratch:/scratch -B $PWD:/data -B $KRAKEN_DEFAULT_DB:/kraken-database sneakernet.0.11.2.sif SneakerNetPlugins.pl --numcpus $NSLOTS --no email --no transfer --no save --no immediate $outdirAbs

END_OF_SCRIPT
  done;
  #echo "DEBUG"; break;
done
```

This is the perl one-liner I used to extract a table of means and standard deviations from the `time --verbose` output.

```perl -MStatistics::Basic=mean,stddev -MData::Dumper -Mautodie -le '$/=undef; for my $log(glob("rep*/*.log")){open(my $fh, $log); $txt=<$fh>; close $fh; if($log=~/(\d+)\D+(\d+)/){$rep=$1; $cpus=$2;} else{die "ERROR: no cpus or reps in $log filename"} if($txt=~/Elapsed\D+(\d+):(\d+)/){$min=$1; $sec=$2; $time=$min*60+$sec}else{die "ERROR: no time in $log"} if($txt=~/Maximum resident set size\D+(\d+)/){$size=$1} else{die "ERROR: no size in $Log"} $size{$cpus}[$rep-1]=$size; $time{$cpus}[$rep-1]=$time;} for my $cpus(sort{$a<=>$b} keys(%time)){ print join("\t", $cpus, mean(@{$size{$cpus}})+0, stddev(@{$size{$cpus}})+0, mean(@{$time{$cpus}})+0, stddev(@{$time{$cpus}})+0 );}' | column -t```

**Comment by lskatz** [comment]
In retrospect, I have summarized these findings into the documentation here: https://github.com/lskatz/SneakerNet/blob/master/docs/INSTALL.md#resources

**Comment by lfaller** [comment]
Thanks for summarizing your benchmark results! I think it'll be helpful for new users to get started to have that kind of information!
