### ISSUE TITLE
transferFilesToRemoteComputers.pl bug

### ISSUE THREAD

**Issue by kapsakcj** [lskatz/SneakerNet#58]
**Describe the bug**
`transferFilesToRemoteComputers.pl` Does not transfer files to the CE, despite the routing information being correctly listed in the SampleSheet.csv and samples.tsv.

This started occuring after this big commit to the master branch from last week. https://github.com/lskatz/SneakerNet/commit/513b9ecd516b724d0f492103ff6779932cf51db9

It has affected the two latest sequencing runs, MN0344-21-003 and M3235-21-002

BUT I have found the cause of this issue and the fix.

Cause of the issue:
https://github.com/lskatz/SneakerNet/blob/513b9ecd516b724d0f492103ff6779932cf51db9/SneakerNet.plugins/transferFilesToRemoteComputers.pl#L110

There is something wrong with the logic in this conditional. It seems to always run the ELSE part of the IF/ELSE statement and won't run the lines under IF statement.

The fix is to undo the change from the commit, and change it back to the way it was:
`if($$settings{'force-transfer'} || grep {/calcengine/i} @route ){`

**To Reproduce**
* I ran `transferFilesToRemoteComputers.pl` on M3235-20-002 (in SN repo) with the new version (1.7) of the script included in the above-mentioned commit.
* I received this in the output for all samples, despite routing info being listed for 7 of the samples 
```
transferFilesToRemoteComputers.pl: Note: The route for 2014C-3599-M3235-21-002 was not listed in the sample sheet.
```
Nothing was transferred to the CE.

Fix:
* I reverted the code on line 110 to the previous version, re-ran the script, and everything transferred as expected (7 samples transferred; other samples without routing info were not transferred)
 

**Expected behavior**
fastq's get transferred to the CE when routing info is listed in the SampleSheet.csv

**Desktop (please complete the following information):**
edlb-sneakernet user on M3

**Additional context**

**Comment by kapsakcj** [comment]
I have already edited the script in the local git repo `~/bin/SneakerNet/SneakerNet.plugins/transferFilesToRemoteComputers.pl` and tested that it works, but I have not committed the change.

Was hoping to chat with you about the next steps.

**Comment by lskatz** [comment]
Addressed in https://github.com/lskatz/SneakerNet/commit/8a7912aa04cbe2e6005f52493beb2898c2b5b6af
